### PR TITLE
[CI] upgrade-go 1.15 -> 1.16

### LINKED ISSUE #38: [CI] Upgrade Go from v1.15 -> v1.16 in workflow scripts
**Is your feature request related to a problem? Please describe.**
The readme of this repository and guidance from rosetta-spec states we should use a `v1.16` release of Go; currently our CI tools use `v1.15`. 

I didn't observe any issues in the pipeline due to using a v1.15 release; it seems like a logical decision to align the CI pipeline with our development & eventually deployment environments.  

**Describe the solution you'd like**
Change the go version we define in [.github/workflows/ci.yaml ](https://github.com/rosetta-dogecoin/rosetta-dogecoin/blob/main/.github/workflows/ci.yml) from `1.15` -> `1.16`

**Describe alternatives you've considered**
We could do nothing; we could also start creating separate workflows if we have an interest in tracking our changes across multiple environment configurations, which could be interesting.

### PR DESCRIPTION
**Pull request by solo-fish**
Tiny PR to resolve #38

It upgrades the version of Go used by our CI tools from `v1.15` to the recommended `v1.16`.

### Motivation
The rosetta-specification & this repository's readme both state dependency on a `v1.16` release of Go; our CI workflow is using `v1.15`.

### Solution
Upgrade the version of Go defined in [.github/workflows/ci.yaml](https://github.com/rosetta-dogecoin/rosetta-dogecoin/blob/main/.github/workflows/ci.yml) from `v1.15` to the recommended `v1.16`.

### Testing
Ran the changes in development branch; verified that the tests are executing & failures are expected per state of implementation. ([CI run](https://github.com/solo-fish/rosetta-dogecoin/runs/2434554304?check_suite_focus=true))

### Open questions
Could we depend on some CI workflows controlled by a `rosetta` impl or spec? Potentially one-less maintenance requirement.

### CODE REVIEW

**Comment by patricklodder** [comment]
Hi! Thanks for this. Unfortunately I had to manually approve the CI trigger because this was your first contrib, so results came in only after I realized I had to do that. Sorry about the delay.

I'm not entirely sure what is going wrong with some of the mock parsing right now - and even though "it isn't broken", 1.16 compatibility is of course a desirable thing. Any idea why this is happening now but not with 1.15?

**Comment by solo-fish** [comment]
Hi @patricklodder - hmm... the failures seem related to #23 

```
--- Expected
+++ Actual
@@ -41,3 +41,3 @@
Account: (*types.AccountIdentifier)({
      -    Address: (string) (len=42) "tb1q3r8xjf0c2yazxnq9ey3wayelygfjxpfqjvj5v7",
      +    Address: (string) (len=44) "tdge1q3r8xjf0c2yazxnq9ey3wayelygfjxpfqmg6g08",
 SubAccount: (*types.SubAccountIdentifier)(<nil>),
@@ -66,3 +66,3 @@
Account: (*types.AccountIdentifier)({
      -    Address: (string) (len=42) "tb1qjsrjvk2ug872pdypp33fjxke62y7awpgefr6ua",
      +    Address: (string) (len=44) "tdge1qjsrjvk2ug872pdypp33fjxke62y7awpgsdtxly",
 SubAccount: (*types.SubAccountIdentifier)(<nil>),

```

I can look into this a bit more this weekend, I was curious to learn about bech32

```

expected: &types.ConstructionParseResponse{Operations:[]*types.Operation{(*types.Operation)(0xc0000ab200), (*types.Operation)(0xc0000ab260), (*types.Operation)(0xc0000ab2c0)}, AccountIdentifierSigners:[]*types.AccountIdentifier{}, Metadata:map[string]interface {}(nil)}

actual  : &types.ConstructionParseResponse{Operations:[]*types.Operation{(*types.Operation)(0xc0000ab440), (*types.Operation)(0xc0000ab4a0), (*types.Operation)(0xc0000ab500)}, AccountIdentifierSigners:[]*types.AccountIdentifier{}, Metadata:map[string]interface {}(nil)}

```

**Comment by solo-fish** [comment]
@patricklodder - could you rerun the CI pipeline against the current `HEAD ` of `main`? I'd do it but seems I'm lacking permissions; while the last run was passing it seems something has changed in the past 12 days and your latest-commit is throwing the same errors, as well. 

[Example](https://github.com/solo-fish/rosetta-dogecoin/runs/2434531748?check_suite_focus=true) from my development branch that is mirroring `main`

**Comment by patricklodder** [comment]
Done. Strangest thing!

**Comment by solo-fish** [comment]
> Done. Strangest thing!

Strange indeed.

Very knew to this space, however, in my experience this is indictive of a breaking change in some package or service-dependency. 

I see in one of our tests we're expecting that some request will return a `500 service error` - which is not the case
```
Error:      	"json: cannot unmarshal object into Go struct field BlockV1.result.tx 
of type string: error decoding response body: error fetching block by hash 00000000c937983704a73af28acdec37b049d214adbda81d7e2a3dd146f6ed09: 
unable to get current block" does not contain "invalid response: 500 Internal Server Error"
```
I'll need to look into this further but I was curious if you could explain or share some resources that give insight into our network architecture in the context of an isolated test run.

RDGC_mental_model

This is my current mental model, I'm assuming the ??? is either the bit/dogecoin daemon, perhaps you could correct any misunderstandings I may have here if not too inconvenient for yourself. 

Looking further at the variety of failures I can't help but think that we're missing something blatant; if not, there's a handful of different issues that potentially would require isolated DD.

**Comment by patricklodder** [comment]
shasum needs to get updated. I get this error on build-local:

```
 > [rosetta-builder  5/10] RUN curl -fsSL "https://golang.org/dl/go1.16.2.linux-amd64.tar.gz" -o golang.tar.gz   && echo "9a58494e8da722c3aef248c9227b0e9c528c7318309827780f16220998180a0d golang.tar.gz" | sha256sum -c -   && tar -C /usr/local -xzf golang.tar.gz   && rm golang.tar.gz:
#13 9.762 golang.tar.gz: FAILED
#13 9.762 sha256sum: WARNING: 1 computed checksum did NOT match
```

**Comment by solo-fish** [comment]
ACK - will fix

**Pull request closed without merging**
