### PR TITLE
RPC Integration issue - GetBlock

### PR DESCRIPTION
**Pull request by RichDevX**
Fixes # 17

### Motivation

The getBlock function in the bitcoin package isn't compatible with the Dogecoin Core v1.14.3 JSON-RPC implementation.

### Solution

When getBlock is called, two "getblock" requests are sent to the Dogecoin JSON-RPC interface, one with the verbosity parameter set to true to get block information, and the other with the verbosity parameter set to false to get a serialized block. To get transaction information, the transactions in the serialized block are decoded by sending a "decoderawtransaction" request for each transaction in the block.

### CODE REVIEW

**Comment by patricklodder** [comment]
Currently this synchronizes for me for all v1 blocks. Is there anything particular that you'd still want to change, re: WIP?

**Comment by RichDevX** [comment]
I was still in the process of figuring out what to do with auxpow blocks. I have been informed that langerhans is working on a btcd port, so it's probably best to use the wire package in that with the existing code instead of doing something else.

**Review by patricklodder — APPROVED** [review]
For now, only supporting v1 block sync is already a huge step in the right direction and helps us to parallelize development, so I will approve this.

I have a couple of notes on this PR, but those should not block further development right now; I will just list them as issues instead:

- Bring back configuration changes from /dogecoin/configuration.go
- Don't put dogecoin-specific code under a bitcoin nomer - since I feel we started doing this too early, this is something to pick back up later when we have a better working implementation.

This PR gives us a cleaner path than #18, so I am selecting this alternative over that one.

**Comment by patricklodder** [comment]
> I have been informed that langerhans is working on a btcd port, so it's probably best to use the wire package in that with the existing code instead of doing something else.

The work done by @langerhans is not guaranteed to be a maintained library in the future, but the wire-specific code has been said to work well, so I figured we can use it as a guidance to do the implementation of v2-serialized blocks :-)

**Comment by godcloutier** [comment]
I did add a pull request with the trezor dogecoin parser who is working pretty well, I might need to redo the PR but you can look into it only 3 function added

**Pull request merged**
