### PR TITLE
RPC Integration issue - GetBlock

### PR DESCRIPTION
**Pull request by xanimo**
Fixes # .

### Solution
Change blockVerbosity from int to bool and add duplicate var for txVerbosity.

Add RawTransactionResponse type in dogecoin types.go.

Add GetRawTransaction func for replacing the txid in dogecoin.Block.Txs with raw transactions not included in getblock.

Add missing files from bitcoin package to dogecoin and remove dir from application.

Add configuration folder back so we can import it how coinbase does.  Currently replacing it in go.mod to point to our directory although its stilling pulling from dogecoin pkg.

Added 1000 & 100000 block in client_fixtures for test prep.

### CODE REVIEW

**Comment by patricklodder** [comment]
> I'm not getting that JSON complaint but I'm several commits deep past this and not certain I should push what I have.

Yeah just push what you have into the draft so we can look at where it has trouble. Don't be shy :-)

**Comment by xanimo** [comment]
So this has been an interesting development.  I've tried swapping ports, adding ports, exposing ports and none seem to reflect in container debug.log.  It always fails on testnet online when trying to connect to 44555.  I also found others who've had issues with rpc inside a container specifically and then making sure the corresponding endpoint is listening on the correct address.  My container listens on 172.17.0.2 for instance.  That aside, dogecoind is doing its thing, testnet3 logs look clean, go on forever but I've not had the patience to let it sync past mid 30%.  
Screenshot (378)

**Comment by xanimo** [comment]
I'm going to try to run a full node on this environment, I think that may be my issue.

**Comment by patricklodder** [comment]
The bind error failure is only for ipv6 inside the container, for 0.0.0.0 ipv4 binds, it does not error out. Since you're mentioning you're using ipv4, this is not an issue.

**Comment by xanimo** [comment]
I'll revert the port swap.  Thanks for your feedback.  Can you give me your thoughts on what's going on here if you've made any progress?  

I wish I was more knowledgeable in golang and blockchain in general.  Feeling a bit overwhelmed. 😅

**Comment by xanimo** [comment]
I know their are tons of unnecessary changes in here I'm just trying to work it out.  And I finally got a different error! :D

**Comment by patricklodder** [comment]
> I know their are tons of unnecessary changes in here I'm just trying to work it out. And I finally got a different error! :D

This is ok. We should make a separate issue for the hardcoded absolute path to be able to run outside of docker.

**Comment by xanimo** [comment]
> > I know their are tons of unnecessary changes in here I'm just trying to work it out. And I finally got a different error! :D
> 
> This is ok. We should make a separate issue for the hardcoded absolute path to be able to run outside of docker.

Building the binary and exporting it to a local app folder with all the deps to mimic the docker layout actually helped me debug and get past that initial error.  Or at least gain some clarity into how everything is working.  It's still unfortunately broken though.

**Comment by xanimo** [comment]
I guess that last commit was unnecessary but for some reason it said the one before was 2 commits behind upstream/main so better safe than sorry.

I've simplified the changes I made in order to increase chances of this pr merged with main.  In the built docker container we are no longer receiving the JSON complaint about not receiving a bool but now with your patch enabled we are encountering cannot unmarshal string into Go struct field Block.result.tx:

Screenshot (380)

Is this re the txs returned as object or array and it throw type error?

When run locally offline with your patch enabled we are still encountering:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x973adb]

goroutine 8 [running]:
github.com/rosetta-dogecoin/rosetta-dogecoin/dogecoin.(*Client).post(0x0, 0xe72258, 0xc00003c500, 0xc7575d, 0x11, 0x127cee0, 0x0, 0x0, 0xe659a0, 0xc000592100, ...)
        /home/xanimo/source/repos/rosetta-dogecoin-backup/dogecoin/client.go:825 +0x1fb
github.com/rosetta-dogecoin/rosetta-dogecoin/dogecoin.(*Client).getBlockchainInfo(0x0, 0xe72258, 0xc00003c500, 0x0, 0x0, 0xc000550dc0)
        /home/xanimo/source/repos/rosetta-dogecoin-backup/dogecoin/client.go:381 +0xa5
github.com/rosetta-dogecoin/rosetta-dogecoin/dogecoin.(*Client).getBlockHash(0x0, 0xe72258, 0xc00003c500, 0x0, 0xc000550f5c, 0x2, 0x2, 0x10100000000)
        /home/xanimo/source/repos/rosetta-dogecoin-backup/dogecoin/client.go:398 +0x107
github.com/rosetta-dogecoin/rosetta-dogecoin/dogecoin.(*Client).getBlock(0x0, 0xe72258, 0xc00003c500, 0x0, 0xc000550f5c, 0xc00008b338, 0xc000550f5c)
        /home/xanimo/source/repos/rosetta-dogecoin-backup/dogecoin/client.go:356 +0x67
github.com/rosetta-dogecoin/rosetta-dogecoin/dogecoin.(*Client).NetworkStatus(0x0, 0xe72258, 0xc00003c500, 0x0, 0x2, 0x1)
        /home/xanimo/source/repos/rosetta-dogecoin-backup/dogecoin/client.go:166 +0x55
main.main.func5(0xc000134780, 0x0, 0xe72258, 0xc00003c500, 0xc00012e3d8, 0xc000596420)
        /home/xanimo/source/repos/rosetta-dogecoin-backup/main.go:197 +0x151
created by main.main
        /home/xanimo/source/repos/rosetta-dogecoin-backup/main.go:193 +0xa37
```

I also have a proposal to add back the configuration folder.  I added it back and populated it with our config files and new genesis and param files because it would be easier to import github.com/rosetta-dogecoin/rosetta-dogecoin/configuration than how it's currently set up.  This is just my opinion, I think it's cleaner to have a config folder and to call configuration.Configuration.  I'm currently replacing github.com/coinbase/rosetta-bitcoin/configuration => ./configuration in our go.mod as a temp work around.

**Comment by xanimo** [comment]
It just keeps going and going and going..
Screenshot (424)
Screenshot (423)

**Comment by patricklodder** [comment]
I have merged #19 in favor over this PR, because that commit tree was cleaner. I know both authors collaborated on this, so the credit for the merge on that goes to you both, even if the log doesn't reflect it like that.

@xanimo could you please open a new PR that gives us all the tests you engineered in this PR?

**Pull request closed without merging**
